### ISSUE TITLE
마이페이지: 회원 탈퇴 구현

### ISSUE THREAD

**Issue by uknwns** [codestates/pictureCloud#9]
## Issue 타입

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 상세내용

 - 회원 탈퇴 기능 구현
 - 회원 탈퇴 API 요청 구현

### 예상 소요 시간
- [ ] `0.5h`
- [x] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`

**Comment by hwarang98** [comment]
프로젝트 변경으로 인한 작업 파기
